#! /bin/sh
if [ "$UID" -eq "0" ]; then
	install -v -m 0755 ddns /usr/bin/
	install -v -m 0644 conf/ddns.service /usr/lib/systemd/system/
	if [ ! -f "/etc/ddns.conf" ]; then
	install -v -m 0644 conf/ddns.conf /etc/
	fi
	systemctl daemon-reload
else
	echo "you must run as root"
fi
